// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PrioridadesApi.Data;

#nullable disable

namespace PrioridadesApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251012010936_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("PrioridadesApi.Models.Prioridad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ActualizadaEl")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Completada")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreadaEl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaVencimiento")
                        .HasColumnType("TEXT");

                    b.Property<int>("Nivel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Nivel");

                    b.ToTable("Prioridades");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Completada = false,
                            CreadaEl = new DateTime(2025, 10, 12, 1, 9, 35, 679, DateTimeKind.Utc).AddTicks(1043),
                            Nivel = 3,
                            Titulo = "Entregar tarea Aplicada 1"
                        },
                        new
                        {
                            Id = 2,
                            Completada = false,
                            CreadaEl = new DateTime(2025, 10, 12, 1, 9, 35, 679, DateTimeKind.Utc).AddTicks(1044),
                            Nivel = 2,
                            Titulo = "Hacer backup del proyecto"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
